### ISSUE TITLE
spurious panic due to "unexpected" state change

### ISSUE THREAD

**Issue by mattfenwick** [blackducksoftware/perceptor#111]
```
time="2018-03-20T20:33:44Z" level=error msg="can't start checking hub for image , status is not ScanStatusInHubCheckQueue (ScanStatusRunningHubScan)"
panic: can't start checking hub for image , status is not ScanStatusInHubCheckQueue (ScanStatusRunningHubScan)

goroutine 12 [running]:
github.com/blackducksoftware/perceptor/pkg/core/model.(*Model).GetNextImageFromHubCheckQueue(0xc420230720, 0x2b)
        /workspace/gopath/src/github.com/blackducksoftware/perceptor/pkg/core/model/model.go:154 +0x2ac
github.com/blackducksoftware/perceptor/pkg/core/actions.(*GetInitialHubCheckImage).Apply(0xc4200a2070, 0xc420230720)
        /workspace/gopath/src/github.com/blackducksoftware/perceptor/pkg/core/actions/getinitialhubcheckimage.go:35 +0x55
github.com/blackducksoftware/perceptor/pkg/core.newReducer.func1(0xc4202306c0, 0xc42000ba60, 0xc420230720)
        /workspace/gopath/src/github.com/blackducksoftware/perceptor/pkg/core/reducer.go:54 +0x1ff
created by github.com/blackducksoftware/perceptor/pkg/core.newReducer
        /workspace/gopath/src/github.com/blackducksoftware/perceptor/pkg/core/reducer.go:39 +0x9d
```

**Comment by mattfenwick** [comment]
Should be fixed by https://github.com/blackducksoftware/perceptor-scanner/pull/46
