### ISSUE TITLE
interesting panic

### ISSUE THREAD

**Issue by jayunit100** [blackducksoftware/perceptor#62]
saw this while hacking inside a perceptor container

```
time="2018-02-22T22:53:05Z" level=info msg="INITIALIZING LOGRUS WITH METRICS HOOK [metrics subsystem = laserbeak]"
time="2018-02-22T22:53:05Z" level=info msg=start
time="2018-02-22T22:53:05Z" level=info msg="instantiating perceptor with config: host 34.227.106.252.xip.io, user sysadmin, scan client version , hub version "
time="2018-02-22T22:53:05Z" level=error msg="Error trying to login via form login: Post https://34.227.106.252.xip.io/j_spring_security_check: dial tcp: lookup 34.227.106.252.xip.io on 172.31.6.83:53: no such host."
time="2018-02-22T22:53:05Z" level=error msg="unable to instantiate hub Fetcher: Post https://34.227.106.252.xip.io/j_spring_security_check: dial tcp: lookup 34.227.106.252.xip.io on 172.31.6.83:53: no such host"
time="2018-02-22T22:53:05Z" level=error msg="unable to instantiate percepter: Post https://34.227.106.252.xip.io/j_spring_security_check: dial tcp: lookup 34.227.106.252.xip.io on 172.31.6.83:53: no such host"
panic: Post https://34.227.106.252.xip.io/j_spring_security_check: dial tcp: lookup 34.227.106.252.xip.io on 172.31.6.83:53: no such host
goroutine 1 [running]:
github.com/blackducksoftware/perceptor/pkg/core.RunFromInsideCluster()
        /go/src/github.com/blackducksoftware/perceptor/pkg/core/executable.go:91 +0x40e
main.main()
        /go/src/github.com/blackducksoftware/perceptor/cmd/perceptor/perceptor.go:29 +0x20

```
not sure if its a bubg ? 
![screen shot 2018-02-22 at 5 53 23 pm](https://user-images.githubusercontent.com/826111/36568828-6a03d1ac-17f9-11e8-8e8c-bc298a98e926.png)

[](url)

**Comment by mattfenwick** [comment]
Looks like it's unable to log in to the hub -- and when it's unable to log in to the hub, it panics.
